### ISSUE TITLE
back button in sign up page 

### ISSUE THREAD

**Issue by gaur15** [thestarsahil/Counsellor#69]
**Is your feature request related to a problem? Please describe.**
when I tried opening sign up page and wanted to back there was no option so its convenient if back button is there

**Describe the solution you'd like**
add back button would solve the problem button in extreme right corner

**Describe alternatives you've considered**

**Additional context**

**Comment by thestarsahil** [comment]
Hello, Gaur

Thank you for bringing up the issue and suggesting a solution. It seems that there is currently no back button available on the Sign Up page, which makes it inconvenient for users who want to go back to the previous page.

To address this problem, I suggest adding a back button in the extreme right corner of the Sign Up page. This button would allow users to easily navigate back to the previous page without any hassle.

Alternatively, instead of a back button, you could consider adding a "Cancel" or "Go Back" link at the top or bottom of the page as an alternative solution. This would provide a clear and intuitive way for users to navigate back without cluttering the UI.

Adding a back button or a navigational link will improve the user experience by providing a seamless way to go back and forth between pages.

If you have any additional context or screenshots that could further illustrate the feature request, please provide them. It will help in better understanding the issue and finding an appropriate solution.

Thank you for your contribution and for raising this concern. Let me know if you have any further questions or if there's anything else I can assist you with.

Best regards,
@thestarsahil

**Comment by gaur15** [comment]
Sir I can add "cancel" or "Go back " button.
<img width="328" alt="Screenshot 2023-05-28 102501" src="https://github.com/thestarsahil/Counsellor/assets/133087361/7353d21a-6283-47f1-8f80-c0dd681d05bc">

**Comment by manoranjanonline** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by thestarsahil** [comment]
@gaur15 
Thank you for your contribution to the project! We appreciate your willingness to help out.

At this time, we don't need this fearture to add on , but we will definitely keep it in mind for the future. If we do need your help, we will reach out to you.
